import Papa from 'papaparse';
import { CertificateTemplate, CsvValidationResult, CsvValidationRow } from './types';

export function parseAndValidateCsv(
  csvContent: string,
  template: CertificateTemplate
): CsvValidationResult {
  const parsed = Papa.parse<Record<string, string>>(csvContent, {
    header: true,
    skipEmptyLines: 'greedy',
    transformHeader: (header) => header.trim().toLowerCase(),
  });

  const headers = (parsed.meta.fields || []).map((h) => h.toLowerCase());

  // Determine required columns from template placeholders + email (always needed for identity/delivery)
  const requiredKeys = new Set<string>();
  requiredKeys.add('email');

  for (const placeholder of template.placeholders) {
    const key = placeholder.key.toLowerCase();
    // cert_id is auto-generated by the issuance engine, so not required in CSV
    if (key !== 'cert_id' && placeholder.required) {
      requiredKeys.add(key);
    }
  }

  const missingRequiredColumns: string[] = [];
  for (const requiredKey of Array.from(requiredKeys)) {
    if (!headers.includes(requiredKey)) {
      missingRequiredColumns.push(requiredKey);
    }
  }

  const validRows: CsvValidationRow[] = [];
  const invalidRows: CsvValidationRow[] = [];
  const duplicateRows: CsvValidationRow[] = [];

  // Track duplicates: composite key of email + credential
  const seenCompositeKeys = new Map<string, number>();

  parsed.data.forEach((rawRow, index) => {
    const rowNumber = index + 2; // +1 for 0-index, +1 for header row
    const rowErrors: string[] = [];

    // Clean row data
    const cleanedRow: Record<string, string> = {};
    for (const [key, value] of Object.entries(rawRow)) {
      cleanedRow[key.toLowerCase().trim()] = (value || '').trim();
    }

    // Check required columns
    for (const reqKey of Array.from(requiredKeys)) {
      const val = cleanedRow[reqKey];
      if (!val || val.length === 0) {
        rowErrors.push(`Missing value for required column "${reqKey}"`);
      }
    }

    // Email format validation
    const email = cleanedRow['email'];
    if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      rowErrors.push(`Invalid email address format: "${email}"`);
    }

    // Date format validation if issue_date is present
    const dateVal = cleanedRow['issue_date'] || cleanedRow['date'];
    if (dateVal && isNaN(Date.parse(dateVal))) {
      rowErrors.push(`Unrecognized date format for issue date: "${dateVal}"`);
    }

    // Check duplicate within this batch (same email + same credential)
    const credential = cleanedRow['credential'] || cleanedRow['course'] || '';
    const compositeKey = `${(email || '').toLowerCase()}::${credential.toLowerCase()}`;

    if (email && credential) {
      if (seenCompositeKeys.has(compositeKey)) {
        const prevRow = seenCompositeKeys.get(compositeKey);
        rowErrors.push(
          `Duplicate recipient: ${email} for "${credential}" was already defined at row ${prevRow}`
        );
      } else {
        seenCompositeKeys.set(compositeKey, rowNumber);
      }
    }

    const validationRow: CsvValidationRow = {
      rowNumber,
      data: cleanedRow,
      isValid: rowErrors.length === 0,
      errors: rowErrors,
    };

    if (rowErrors.length === 0) {
      validRows.push(validationRow);
    } else {
      if (rowErrors.some((e) => e.startsWith('Duplicate recipient'))) {
        duplicateRows.push(validationRow);
      }
      invalidRows.push(validationRow);
    }
  });

  const isValid = missingRequiredColumns.length === 0 && invalidRows.length === 0 && validRows.length > 0;

  return {
    totalRows: parsed.data.length,
    validRows,
    invalidRows,
    duplicateRows,
    detectedColumns: headers,
    missingRequiredColumns,
    isValid,
  };
}

/**
 * Generate a sample CSV string matching the template's required & optional fields.
 */
export function generateSampleCsv(template: CertificateTemplate): string {
  const fields = new Set<string>();
  fields.add('name');
  fields.add('credential');
  fields.add('issue_date');
  fields.add('email');

  for (const placeholder of template.placeholders) {
    if (placeholder.key !== 'cert_id') {
      fields.add(placeholder.key.toLowerCase());
    }
  }

  const headerRow = Array.from(fields).join(',');
  const sample1 = [
    'Asha Verma',
    'Advanced Data Analysis',
    '2026-09-14',
    'asha@example.com',
  ];
  const sample2 = [
    'Rohan Iyer',
    'Advanced Data Analysis',
    '2026-09-14',
    'rohan@example.com',
  ];
  const sample3 = [
    'Elena Rostova',
    'Cybersecurity Architect',
    '2026-09-20',
    'elena.rostova@example.org',
  ];

  return [headerRow, sample1.join(','), sample2.join(','), sample3.join(',')].join('\n');
}
