import TemplateDesignerEditor from '@/components/TemplateDesignerEditor';
import { CertificateTemplate } from '@/lib/types';

export default function NewTemplatePage() {
  const newTemplate: CertificateTemplate = {
    id: `template-custom-${Date.now().toString().slice(-4)}`,
    name: 'Custom Certificate Template',
    description: 'Custom certificate layout created in the visual template designer.',
    width: 1056,
    height: 816,
    backgroundStyle: 'executive-gold',
    placeholders: [
      {
        id: 'p-inst',
        key: 'issuer_name',
        label: 'Issuing Institution',
        x: 50,
        y: 18,
        fontSize: 22,
        fontFamily: 'serif',
        fontWeight: 'bold',
        color: '#D4AF37',
        textAlign: 'center',
        required: true,
        sampleValue: 'ACCREDITED CERTIFICATION AUTHORITY',
      },
      {
        id: 'p-name',
        key: 'name',
        label: 'Recipient Name',
        x: 50,
        y: 40,
        fontSize: 34,
        fontFamily: 'serif',
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
        required: true,
        sampleValue: 'Recipient Full Name',
      },
      {
        id: 'p-cred',
        key: 'credential',
        label: 'Credential Awarded',
        x: 50,
        y: 56,
        fontSize: 24,
        fontFamily: 'serif',
        fontWeight: 'bold',
        color: '#F59E0B',
        textAlign: 'center',
        required: true,
        sampleValue: 'Certificate of Distinction & Mastery',
      },
      {
        id: 'p-date',
        key: 'issue_date',
        label: 'Issue Date',
        x: 25,
        y: 78,
        fontSize: 13,
        fontFamily: 'sans',
        fontWeight: 'normal',
        color: '#94A3B8',
        textAlign: 'center',
        required: true,
        sampleValue: '2026-10-02',
      },
      {
        id: 'p-id',
        key: 'cert_id',
        label: 'Certificate Identifier',
        x: 50,
        y: 88,
        fontSize: 12,
        fontFamily: 'mono',
        fontWeight: 'bold',
        color: '#64748B',
        textAlign: 'center',
        required: false,
        sampleValue: 'CERT-2026-000001',
      },
    ],
    qrConfig: {
      x: 82,
      y: 72,
      size: 110,
      darkColor: '#0F172A',
      lightColor: '#FFFFFF',
      includeLabel: true,
      label: 'SCAN TO VERIFY',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  return <TemplateDesignerEditor initialTemplate={newTemplate} isNew={true} />;
}
